# this is used by conda-package.yml
name: build_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Packaging
  - pip
  # Package
  - appdirs
  - bokeh
  - colorcet
  - holoviews
  - ipyevents
  - ipympl
  - k3d
  - matplotlib
  - mergedeep
  - numpy
  - panel
  - param
  - plotly >=4.14.3
  - python
  - scipy
  - sympy
  - vtk
  - msgpack-python
  - adaptive