{% set data = load_setup_py_data() %}

package:
  name: "sympy_plot_backends"
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - packaging
    - appdirs >=1.4.4
    - numpy >=1.21.1
    - sympy >=1.10.1
    - matplotlib-base >3.4.2
    - mergedeep >=1.3.4

test:
  imports:
    - spb
  commands:
    - pip check
  requires:
    - pip

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_family: BSD
  license_file: LICENSE
  summary: {{ data['description'] }}

