name: Conda Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Conda Package Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    env:
      conda-directory: ${{ github.workspace }}/conda
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: 'true'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          conda-build-version: "*"
      - name: Store CONDA variable
        run: |
          echo "CONDA=$CONDA" >> $GITHUB_ENV
      - name: Build conda package
        run: |
          conda build --no-anaconda-upload --no-test recipe -c conda-forge -c defaults
        working-directory: ${{env.conda-directory}}
